# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audiofile < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "0.4"

  on_macos do
    url "https://github.com/marianina8/audiofile/releases/download/v0.4/audiofile_Darwin_all.tar.gz"
    sha256 "dd8fd34a2bfa3a973c01a8070790abd99b26e7d70817f7c314fcc73884b7c5c1"

    def install
      bin.install "audiofile"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marianina8/audiofile/releases/download/v0.4/audiofile_Linux_arm64.tar.gz"
      sha256 "1737e4901f6eac44bde974c5393d9b20557f578e53e1abb107aeb1b1e5a4ef4b"

      def install
        bin.install "audiofile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marianina8/audiofile/releases/download/v0.4/audiofile_Linux_x86_64.tar.gz"
      sha256 "6d20c1239d1fb10afc685857ed0b8bc7c45b18daa4946aca4f1b36089bf56e05"

      def install
        bin.install "audiofile"
      end
    end
  end
end
