# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audiofile < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "0.2"

  on_macos do
    url "https://github.com/marianina8/audiofile/releases/download/v0.2/audiofile_Darwin_all.tar.gz"
    sha256 "d48a99ddbe5e67278f4916a24654fecf89d70caf85bb3117b9779c753c6cb542"

    def install
      bin.install "audiofile"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marianina8/audiofile/releases/download/v0.2/audiofile_Linux_arm64.tar.gz"
      sha256 "b233f5f7a0c975cd78a7c4eecb110590e50c1c01669400d91dbb9b81a493149d"

      def install
        bin.install "audiofile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marianina8/audiofile/releases/download/v0.2/audiofile_Linux_x86_64.tar.gz"
      sha256 "d3bbd261e91128508b38f92e98e68a98af565d82c8ec31dd2ca2b6599a6a3321"

      def install
        bin.install "audiofile"
      end
    end
  end
end
